// GENERATED — do not edit.
// Generated by tools/reference/gen_species_data.py from Cantera 3.2.0 data files:
//   thermo:    nasa_gas.yaml — NASA Glenn database, NASA-7 fits (B.J. McBride, S. Gordon,
//              M.A. Reno, NASA TM-4513, 1993). `note` = source/date code of the fit.
//   transport: gri30.yaml (GRI-Mech 3.0) Lennard-Jones data; liquid-fuel species from the
//              LLNL PRF transport file (Curran, Pitz & Westbrook 2002) — see `source`.
// Regenerate: .venv/bin/python tools/reference/gen_species_data.py

/**
 * Standard-state pressure of every polynomial below, Pa: 1 bar. NASA TM-4513 (McBride et al.
 * 1993) states the ideal-gas standard state is 10^5 Pa, and the generator verified it:
 * s°(298.15 K) matches the CODATA 1-bar key values to 0.0070 J/(mol K) (a 1-atm basis
 * would be off by 0.1094).
 */
export const P_REF_NASA = 100000;

/**
 * Reference pressure that Cantera's nasa_gas.yaml ASSIGNS these same fits, Pa (ck2yaml's default
 * of 1 atm — a mislabel). Cantera oracles must rebuild the species with P_REF_NASA (see
 * tools/reference/thermo_common.py nasa_species()) to agree with this data set.
 */
export const CANTERA_NASA_GAS_P_REF = 101325;

/** One NASA-7 entry: cp/R = a0 + a1 T + a2 T² + a3 T³ + a4 T⁴,
 *  h/RT = a0 + a1 T/2 + a2 T²/3 + a3 T³/4 + a4 T⁴/5 + a5/T,
 *  s°/R = a0 ln T + a1 T + a2 T²/2 + a3 T³/3 + a4 T⁴/4 + a6.
 *  `low` applies for T ≤ tmid (Cantera convention), `high` for T > tmid. Temperatures in K. */
export interface Nasa7Record {
  /** Our species name (core/species.ts). */
  name: string;
  /** Name in nasa_gas.yaml. */
  canteraName: string;
  /** Source/date code of the fit (McBride et al. 1993). */
  note: string;
  tmin: number;
  tmid: number;
  tmax: number;
  low: readonly number[];
  high: readonly number[];
  /** Elemental composition as stored by Cantera (atoms per molecule). */
  composition: Readonly<Record<string, number>>;
  /** Cantera molecular weight, kg/mol (cross-check only; MOLAR_MASS is computed). */
  canteraMolarMass: number;
}

/** NASA-7 data for every species, in SPECIES order. */
export const SPECIES_NASA7: readonly Nasa7Record[] = [
  {
    name: 'N2', canteraName: 'N2', note: 'TPIS78',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [3.53100528, -0.000123660987, -5.02999437e-07, 2.43530612e-09, -1.40881235e-12, -1046.97628, 2.96747468],
    high: [2.95257626, 0.00139690057, -4.92631691e-07, 7.86010367e-11, -4.60755321e-15, -923.948645, 5.87189252],
    composition: { N: 2 }, canteraMolarMass: 0.028014,
  },
  {
    name: 'O2', canteraName: 'O2', note: 'TPIS89',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [3.78245636, -0.00299673415, 9.847302e-06, -9.68129508e-09, 3.24372836e-12, -1063.94356, 3.65767573],
    high: [3.66096083, 0.000656365523, -1.41149485e-07, 2.05797658e-11, -1.29913248e-15, -1215.97725, 3.41536184],
    composition: { O: 2 }, canteraMolarMass: 0.031998,
  },
  {
    name: 'AR', canteraName: 'Ar', note: 'L 6/88',
    tmin: 200, tmid: 6000, tmax: 6000,
    low: [2.5, 0, 0, 0, 0, -745.375, 4.37967491],
    high: [2.5, 0, 0, 0, 0, -745.375, 4.37967491],
    composition: { Ar: 1 }, canteraMolarMass: 0.03995,
  },
  {
    name: 'CO2', canteraName: 'CO2', note: 'L 7/88',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [2.35677352, 0.00898459677, -7.12356269e-06, 2.45919022e-09, -1.43699548e-13, -48371.9697, 9.90105222],
    high: [4.63659493, 0.00274131991, -9.95828531e-07, 1.60373011e-10, -9.16103468e-15, -49024.9341, -1.93534855],
    composition: { C: 1, O: 2 }, canteraMolarMass: 0.044009,
  },
  {
    name: 'H2O', canteraName: 'H2O', note: 'L 8/89',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [4.19864056, -0.0020364341, 6.52040211e-06, -5.48797062e-09, 1.77197817e-12, -30293.7267, -0.849032208],
    high: [2.67703787, 0.00297318329, -7.7376969e-07, 9.44336689e-11, -4.26900959e-15, -29885.8938, 6.88255571],
    composition: { H: 2, O: 1 }, canteraMolarMass: 0.018015,
  },
  {
    name: 'CO', canteraName: 'CO', note: 'TPIS79',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [3.57953347, -0.00061035368, 1.01681433e-06, 9.07005884e-10, -9.04424499e-13, -14344.086, 3.50840928],
    high: [3.04848583, 0.00135172818, -4.85794075e-07, 7.88536486e-11, -4.69807489e-15, -14266.1171, 6.0170979],
    composition: { C: 1, O: 1 }, canteraMolarMass: 0.028009999999999997,
  },
  {
    name: 'H2', canteraName: 'H2', note: 'TPIS78',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [2.34433112, 0.00798052075, -1.9478151e-05, 2.01572094e-08, -7.37611761e-12, -917.935173, 0.683010238],
    high: [2.93286579, 0.000826607967, -1.46402335e-07, 1.54100359e-11, -6.88804432e-16, -813.065597, -1.02432887],
    composition: { H: 2 }, canteraMolarMass: 0.002016,
  },
  {
    name: 'OH', canteraName: 'OH', note: 'TPIS78',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [3.99201543, -0.00240131752, 4.61793841e-06, -3.88113333e-09, 1.3641147e-12, 3615.08056, -0.103925458],
    high: [2.83864607, 0.00110725586, -2.93914978e-07, 4.20524247e-11, -2.42169092e-15, 3943.95852, 5.84452662],
    composition: { H: 1, O: 1 }, canteraMolarMass: 0.017007,
  },
  {
    name: 'H', canteraName: 'H', note: 'L 5/93',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [2.5, 0, 0, 0, 0, 25473.6599, -0.446682853],
    high: [2.50000286, -5.65334214e-09, 3.63251723e-12, -9.1994972e-16, 7.95260746e-20, 25473.6589, -0.446698494],
    composition: { H: 1 }, canteraMolarMass: 0.001008,
  },
  {
    name: 'O', canteraName: 'O', note: 'L 1/90',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [3.1682671, -0.00327931884, 6.64306396e-06, -6.12806624e-09, 2.11265971e-12, 29122.2592, 2.05193346],
    high: [2.54363697, -2.73162486e-05, -4.1902952e-09, 4.95481845e-12, -4.79553694e-16, 29226.012, 4.92229457],
    composition: { O: 1 }, canteraMolarMass: 0.015999,
  },
  {
    name: 'NO', canteraName: 'NO', note: 'TPIS89',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [4.21859896, -0.00463988124, 1.10443049e-05, -9.34055507e-09, 2.80554874e-12, 9845.09964, 2.28061001],
    high: [3.26071234, 0.00119101135, -4.29122646e-07, 6.94481463e-11, -4.03295681e-15, 9921.43132, 6.36900518],
    composition: { N: 1, O: 1 }, canteraMolarMass: 0.030006,
  },
  {
    name: 'N', canteraName: 'N', note: 'L 6/88',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [2.5, 0, 0, 0, 0, 56104.6378, 4.19390932],
    high: [2.41594293, 0.0001748906, -1.19023667e-07, 3.02262387e-11, -2.0360979e-15, 56133.7748, 4.64960986],
    composition: { N: 1 }, canteraMolarMass: 0.014007,
  },
  {
    name: 'IC8H18', canteraName: 'C8H18,isooctane', note: 'X 4/85',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [0.815737338, 0.0732643959, 1.78300688e-05, -6.9358962e-08, 3.21629382e-11, -30477.2862, 24.1509994],
    high: [15.9899273, 0.055318479, -1.95267072e-05, 3.11779172e-09, -1.85312577e-13, -35875.7973, -60.1161414],
    composition: { C: 8, H: 18 }, canteraMolarMass: 0.114232,
  },
  {
    name: 'NC7H16', canteraName: 'C7H16,n-heptane', note: 'X10/85',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [11.1532484, -0.00949415433, 0.000195571181, -2.4975252e-07, 9.84873213e-11, -26771.1735, -15.909611],
    high: [18.5354704, 0.0391420468, -1.38030268e-05, 2.22403874e-09, -1.3345258e-13, -31950.0783, -70.190284],
    composition: { C: 7, H: 16 }, canteraMolarMass: 0.100205,
  },
  {
    name: 'CH4', canteraName: 'CH4', note: 'L 8/88',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [5.14987613, -0.0136709788, 4.91800599e-05, -4.84743026e-08, 1.66693956e-11, -10246.6476, -4.64130376],
    high: [1.63552643, 0.0100842795, -3.36916254e-06, 5.34958667e-10, -3.15518833e-14, -10005.6455, 9.99313326],
    composition: { C: 1, H: 4 }, canteraMolarMass: 0.016042999999999998,
  },
  {
    name: 'C3H8', canteraName: 'C3H8', note: 'L 6/90',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [4.2110262, 0.00171599803, 7.06183472e-05, -9.19594116e-08, 3.64421372e-11, -14381.2106, 5.60930491],
    high: [6.66789363, 0.0206120214, -7.36553027e-06, 1.18440761e-09, -7.0695321e-14, -16274.8521, -13.1859503],
    composition: { C: 3, H: 8 }, canteraMolarMass: 0.044097000000000004,
  },
  {
    name: 'C2H5OH', canteraName: 'C2H5OH', note: 'L 8/88',
    tmin: 200, tmid: 1000, tmax: 6000,
    low: [4.85868178, -0.0037400674, 6.95550267e-05, -8.86541147e-08, 3.5168443e-11, -29996.1309, 4.80192294],
    high: [6.5628977, 0.0152034264, -5.38922247e-06, 8.62150224e-10, -5.12824683e-14, -31525.7984, -9.47557644],
    composition: { C: 2, H: 6, O: 1 }, canteraMolarMass: 0.046069000000000006,
  },
];

/** Lennard-Jones / Stockmayer transport parameters (CHEMKIN customary units). */
export interface TransportRecord {
  name: string;
  /** 0 = atom, 1 = linear, 2 = nonlinear. */
  geometry: 0 | 1 | 2;
  /** Potential well depth ε/k_B, K. */
  wellDepth: number;
  /** Collision diameter σ, Å (1e-10 m). */
  diameter: number;
  /** Permanent dipole moment, Debye. */
  dipole: number;
  /** Polarizability, Å³. */
  polarizability: number;
  /** Rotational relaxation collision number Z_rot at 298 K. */
  rotRelax: number;
  source: string;
}

/** Transport parameters for every species, in SPECIES order. */
export const SPECIES_TRANSPORT: readonly TransportRecord[] = [
  { name: 'N2', geometry: 1, wellDepth: 97.53, diameter: 3.621, dipole: 0, polarizability: 1.76, rotRelax: 4, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'O2', geometry: 1, wellDepth: 107.4, diameter: 3.458, dipole: 0, polarizability: 1.6, rotRelax: 3.8, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'AR', geometry: 0, wellDepth: 136.5, diameter: 3.33, dipole: 0, polarizability: 0, rotRelax: 0, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'CO2', geometry: 1, wellDepth: 244, diameter: 3.763, dipole: 0, polarizability: 2.65, rotRelax: 2.1, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'H2O', geometry: 2, wellDepth: 572.4, diameter: 2.605, dipole: 1.844, polarizability: 0, rotRelax: 4, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'CO', geometry: 1, wellDepth: 98.1, diameter: 3.65, dipole: 0, polarizability: 1.95, rotRelax: 1.8, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'H2', geometry: 1, wellDepth: 38, diameter: 2.92, dipole: 0, polarizability: 0.79, rotRelax: 280, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'OH', geometry: 1, wellDepth: 80, diameter: 2.75, dipole: 0, polarizability: 0, rotRelax: 0, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'H', geometry: 0, wellDepth: 145, diameter: 2.05, dipole: 0, polarizability: 0, rotRelax: 0, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'O', geometry: 0, wellDepth: 80, diameter: 2.75, dipole: 0, polarizability: 0, rotRelax: 0, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'NO', geometry: 1, wellDepth: 97.53, diameter: 3.621, dipole: 0, polarizability: 1.76, rotRelax: 4, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'N', geometry: 0, wellDepth: 71.4, diameter: 3.298, dipole: 0, polarizability: 0, rotRelax: 0, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'IC8H18', geometry: 2, wellDepth: 458.5, diameter: 6.414, dipole: 0, polarizability: 0, rotRelax: 1, source: 'LLNL prf_tran_dat_v1b.txt (Curran et al. 2002), entry \'WJP\'' },
  { name: 'NC7H16', geometry: 2, wellDepth: 459.6, diameter: 6.253, dipole: 0, polarizability: 0, rotRelax: 1, source: 'LLNL prf_tran_dat_v1b.txt (Curran et al. 2002), entry \'TCPC\'' },
  { name: 'CH4', geometry: 2, wellDepth: 141.4, diameter: 3.746, dipole: 0, polarizability: 2.6, rotRelax: 13, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'C3H8', geometry: 2, wellDepth: 266.8, diameter: 4.982, dipole: 0, polarizability: 0, rotRelax: 1, source: 'gri30.yaml (GRI-Mech 3.0 transport data)' },
  { name: 'C2H5OH', geometry: 2, wellDepth: 470.6, diameter: 4.41, dipole: 0, polarizability: 0, rotRelax: 1.5, source: 'LLNL prf_tran_dat_v1b.txt, entry \'NMM\' (Marinov 1999)' },
];
