import { describe, expect, it } from 'vitest';
import type { EngineSnapshot } from '../../physics/core/snapshot';
import { GasFlowModel } from './flow';
import { insideChamber } from './geometry';
import { snap, testSpec, TEST_R } from './test-utils';
import { TracerState, TracerSystem } from './tracers';

const spec = testSpec();
const NONE: [number, number, number] = [0, 0, 0];

/** Drive a tracer system through snapshots generated by `gen(t)` with frame step dt. */
function drive(gen: (t: number) => EngineSnapshot, T: number, dt: number, sys = new TracerSystem(spec), flow = new GasFlowModel(spec)) {
  let t = 0;
  let s = gen(0);
  flow.update(s, 0);
  sys.update(s, 0, flow, NONE, 0, false);
  while (t < T - 1e-12) {
    const d = Math.min(dt, T - t);
    t += d;
    s = gen(t);
    flow.update(s, d);
    sys.update(s, d, flow, NONE, 0, false);
  }
  return { sys, flow };
}

const intake = (mdot: number) => (t: number) =>
  snap({
    t, phase: 'gas-exchange', intakeLift: 6e-3, intakeMassFlow: mdot, clearanceHeight: 0.06, volume: Math.PI * TEST_R ** 2 * 0.06,
    mass: 3e-4, pressure: 0.9e5, intakeManifoldPressure: 0.95e5, temperatureMean: 330,
  });

describe('TracerSystem', () => {
  it('spawn count = ∫|ṁ| dt / parcel mass', () => {
    const { sys } = drive(intake(0.02), 4e-3, 1e-4);
    const expected = (0.02 * 4e-3) / sys.parcelMass;
    expect(Math.abs(sys.count - expected)).toBeLessThanOrEqual(2);
    expect(sys.count).toBeGreaterThan(50);
  });

  it('slow motion invariance: the same simulated interval gives the same count for any frame split', () => {
    const a = drive(intake(0.02), 4e-3, 4e-5).sys.count; // slow motion: tiny sim steps per frame
    const b = drive(intake(0.02), 4e-3, 2e-3).sys.count; // fast playback
    expect(Math.abs(a - b)).toBeLessThanOrEqual(2);
  });

  it('intake inflow: particles come down the port, then jet out of the OPEN arc into the chamber', () => {
    // run until the first parcels leave the curtain, then 60 µs more (jets still fresh)
    const sys = new TracerSystem(spec);
    const flow = new GasFlowModel(spec);
    let t = 0;
    let s = intake(0.02)(0);
    flow.update(s, 0);
    sys.update(s, 0, flow, NONE, 0, false);
    let firstOut = -1;
    while (t < 5e-3 && (firstOut < 0 || t < firstOut + 6e-5)) {
      t += 1e-5;
      s = intake(0.02)(t);
      flow.update(s, 1e-5);
      sys.update(s, 1e-5, flow, NONE, 0, false);
      if (firstOut < 0) for (let i = 0; i < sys.count; i++) if (sys.state[i] === TracerState.InCylinder) { firstOut = t; break; }
    }
    expect(firstOut).toBeGreaterThan(0);
    const v = spec.intakeValve;
    const a = v.seatInnerDiameter / 2;
    const d = v.shroudDirection;
    let portIn = 0, inCyl = 0, fresh = 0, dirSum = 0;
    for (let i = 0; i < sys.count; i++) {
      const x = sys.position[3 * i], y = sys.position[3 * i + 1], z = sys.position[3 * i + 2];
      // every intake parcel was assigned a curtain angle on the open arc
      expect(Math.abs(sys.psi[i] - d)).toBeLessThanOrEqual(Math.PI / 2 + 1e-6);
      if (sys.state[i] === TracerState.PortIn) {
        portIn++;
        expect(y).toBeGreaterThan(0);
      } else if (sys.state[i] === TracerState.InCylinder) {
        inCyl++;
        expect(insideChamber(x, y, z, TEST_R * 1.0001, 0.06 + 1e-9)).toBe(true);
        // parcels that just left the curtain: jet along their curtain angle, toward the open side
        {
          expect(Math.hypot(x - v.position[0], z - v.position[1])).toBeGreaterThan(a - 1e-6);
          const jx = sys.jet[3 * i], jz = sys.jet[3 * i + 2];
          const jh = Math.hypot(jx, jz);
          expect(jh).toBeGreaterThan(0);
          expect((jx * Math.cos(sys.psi[i]) + jz * Math.sin(sys.psi[i])) / jh).toBeGreaterThan(0.99);
          dirSum += (jx * Math.cos(d) + jz * Math.sin(d)) / jh;
          fresh++;
        }
      }
    }
    expect(portIn + inCyl).toBe(sys.count);
    expect(portIn).toBeGreaterThan(0);
    expect(fresh).toBeGreaterThan(3);
    // mean cos over a uniformly used 180° arc = 2/π ≈ 0.64
    expect(dirSum / fresh).toBeGreaterThan(0.4);
  });

  it('backflow (ṁ < 0) reverses: particles leave the cylinder through the intake valve and go up the port', () => {
    const { sys } = drive(intake(-0.02), 4e-3, 1e-4);
    expect(sys.count).toBeGreaterThan(20);
    let out = 0, portIn = 0;
    for (let i = 0; i < sys.count; i++) {
      if (sys.state[i] === TracerState.PortOut) {
        out++;
        expect(sys.position[3 * i + 1]).toBeGreaterThanOrEqual(0);
      }
      if (sys.state[i] === TracerState.PortIn) portIn++;
    }
    expect(out).toBeGreaterThan(0);
    expect(portIn).toBe(0);
  });

  it('exhaust blowdown: hot parcels drain to the exhaust valve', () => {
    const gen = (t: number) =>
      snap({ t, phase: 'gas-exchange', exhaustLift: 5e-3, exhaustMassFlow: 0.05, clearanceHeight: 0.1, volume: Math.PI * TEST_R ** 2 * 0.1, mass: 5e-4, temperatureMean: 1300 });
    const { sys } = drive(gen, 2e-3, 1e-4);
    expect(sys.count).toBeGreaterThan(10);
    let hot = 0, nearOrOut = 0;
    for (let i = 0; i < sys.count; i++) {
      if (sys.hot[i]) hot++;
      if (sys.state[i] === TracerState.PortOut || sys.state[i] === TracerState.ToValve) nearOrOut++;
      expect(sys.valve[i]).toBe(1);
    }
    expect(hot).toBe(sys.count);
    expect(nearOrOut).toBe(sys.count);
  });

  it('in-cylinder tracers stay inside the chamber under compression, swirl and turbulence', () => {
    const sys = new TracerSystem(spec);
    const flow = new GasFlowModel(spec);
    // fill during intake, then compress (h: 0.06 → 0.02) with strong turbulence
    drive(intake(0.03), 5e-3, 1e-4, sys, flow);
    let t = 5e-3;
    for (let k = 1; k <= 100; k++) {
      const h = 0.06 - 0.04 * (k / 100);
      const s = snap({ t: t + 1e-4, clearanceHeight: h, volume: Math.PI * TEST_R ** 2 * h, flame: { turbulenceIntensity: 8 } });
      flow.update(s, 1e-4);
      sys.update(s, 1e-4, flow, NONE, 0, false);
      t += 1e-4;
    }
    let n = 0;
    for (let i = 0; i < sys.count; i++) {
      if (sys.state[i] !== TracerState.InCylinder) continue;
      n++;
      const x = sys.position[3 * i], y = sys.position[3 * i + 1], z = sys.position[3 * i + 2];
      expect(insideChamber(x, y, z, TEST_R * 1.0001, 0.02 + 1e-6)).toBe(true);
    }
    expect(n).toBeGreaterThan(50);
  });

  it('the flame front marks the parcels it passes (sphere ∩ chamber only)', () => {
    const sys = new TracerSystem(spec);
    const flow = new GasFlowModel(spec);
    drive(intake(0.03), 5e-3, 1e-4, sys, flow);
    const c: [number, number, number] = [0, -0.002, TEST_R - 0.004];
    const r = 0.03;
    const s = snap({ t: 5.1e-3, clearanceHeight: 0.06 });
    flow.update(s, 1e-4);
    sys.update(s, 1e-4, flow, c, r, false);
    let burned = 0, unburned = 0;
    for (let i = 0; i < sys.count; i++) {
      if (sys.state[i] !== TracerState.InCylinder) continue;
      const x = sys.position[3 * i], y = sys.position[3 * i + 1], z = sys.position[3 * i + 2];
      const inside = Math.hypot(x - c[0], y - c[1], z - c[2]) <= r;
      if (inside) {
        expect(Number.isNaN(sys.burnTime[i])).toBe(false);
        burned++;
      } else {
        expect(Number.isNaN(sys.burnTime[i])).toBe(true);
        unburned++;
      }
    }
    expect(burned).toBeGreaterThan(0);
    expect(unburned).toBeGreaterThan(0);
  });

  it('respects capacity and reset', () => {
    const sys = new TracerSystem(spec, 64);
    drive(intake(0.2), 5e-3, 1e-4, sys);
    expect(sys.count).toBe(64);
    sys.reset();
    expect(sys.count).toBe(0);
  });
});
